/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top keywords
         * @description Return the most frequent business keywords.
         */
        get: operations["keywords_api_analytics_keywords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available platforms */
        get: operations["platforms_api_analytics_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/rating-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rating distribution */
        get: operations["rating_distribution_api_analytics_rating_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/sentiment-by-platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform sentiment */
        get: operations["sentiment_by_platform_api_analytics_sentiment_by_platform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard summary
         * @description Return overall review statistics.
         */
        get: operations["summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Monthly sentiment trends
         * @description Return monthly sentiment trends for dashboard visualisation.
         */
        get: operations["trends_api_analytics_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/rag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * RAG / RAGAS evaluation
         * @description Faithfulness, answer relevancy and other RAG pipeline metrics from evaluate/evaluate_llm_vs_rag.py. Returns available=false if that script hasn't been run yet.
         */
        get: operations["rag_evaluation_api_evaluation_rag_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/retrieval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieval evaluation
         * @description TF-IDF vs semantic search (FAISS) retrieval quality and latency.
         */
        get: operations["retrieval_evaluation_api_evaluation_retrieval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sentiment classifier evaluation
         * @description Model comparison, confusion matrices and significance tests for the five sentiment classifiers.
         */
        get: operations["sentiment_evaluation_api_evaluation_sentiment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Reports whether data/index/LLM are actually available, not just that the process is alive.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a CSV of customer feedback
         * @description Validates the file, stores the valid rows for the signed-in user's organisation and queues analysis. Requires a `text` column; `external_id`, `created_at`, `rating` and `platform` are optional. Rejected rows are reported per row and do not stop the import. Re-uploading an identical file creates nothing and returns the original import.
         */
        post: operations["create_import_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status and counts for one import */
        get: operations["read_import_api_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status of a background job */
        get: operations["read_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rag/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question about customer complaints */
        post: operations["chat_api_rag_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic search over customer reviews */
        post: operations["search_api_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/analyse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Full review analysis pipeline
         * @description Sentiment, complaint category, similar reviews and an LLM-generated business summary — everything the Analyse page shows.
         */
        post: operations["analyse_api_sentiment_analyse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/batch-predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sentiment for many reviews at once
         * @description Used by the Upload page to score an uploaded CSV. Capped at 200 rows per call.
         */
        post: operations["batch_api_sentiment_batch_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare all five sentiment models on one review */
        post: operations["compare_api_sentiment_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available sentiment models */
        get: operations["models_api_sentiment_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sentiment only, one model */
        post: operations["predict_api_sentiment_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Category breakdown
         * @description Counts, share and sentiment split per category, largest first. Grouped by the stable category key, so a renamed category keeps one row. The entry with a null `category_key` holds results with no category - unclassified items and those the sentiment gate skipped.
         */
        get: operations["read_category_breakdown_api_v1_analytics_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Headline metrics
         * @description Volume, sentiment split, unclassified share and average rating for one organisation. Percentages are of *analysed* feedback, so they are not diluted by items the worker has not reached yet.
         */
        get: operations["read_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feedback volume over time
         * @description Counts per day, week or month, bucketed with date_trunc in PostgreSQL. Feedback with no date of its own is grouped by when it was ingested, so the trend adds up to the summary. Periods with no feedback are absent rather than zero-filled.
         */
        get: operations["read_trend_api_v1_analytics_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Sets the session cookie. 401 with the same message for an unknown email and a wrong password; 403 for a disabled account.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Ends the session and clears the cookie. Succeeds whether or not anyone was signed in.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description The user's email and the organisation they act for, with their role. `organisation` is null for a user who belongs to no organisation. 401 when not signed in.
         */
        get: operations["read_current_user_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and a new organisation
         * @description Creates a user, a new organisation they own, and signs them in by setting the session cookie. Registration always creates a *new* organisation; it cannot join an existing one. 422 for an invalid detail, 409 if the email already has an account.
         */
        post: operations["register_account_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Categories available to this organisation
         * @description The active taxonomy: this organisation's own categories plus the shared defaults. Retired research categories are excluded here, while the breakdown above still reports them if historical results reference them.
         */
        get: operations["read_categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feedback
         * @description One organisation's feedback, newest first, with its current analysis. Every filter is applied in the database. Items not yet analysed are included with null analysis fields; use `analysed=false` to find them.
         */
        get: operations["list_items_api_v1_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One piece of feedback */
        get: operations["read_item_api_v1_feedback__feedback_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent imports
         * @description This organisation's imports, newest first, with the counts each produced.
         */
        get: operations["list_imports_api_v1_imports_get"];
        put?: never;
        /**
         * Upload a CSV of customer feedback
         * @description Validates the file, stores the valid rows for the signed-in user's organisation and queues analysis. Requires a `text` column; `external_id`, `created_at`, `rating` and `platform` are optional. Rejected rows are reported per row and do not stop the import. Re-uploading an identical file creates nothing and returns the original import.
         */
        post: operations["create_import_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One import */
        get: operations["read_import_api_v1_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One background job
         * @description Status, attempts and the analysis result summary. `error` is a short message, never internal detail.
         */
        get: operations["read_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyseResponse */
        AnalyseResponse: {
            analysis: components["schemas"]["ReviewAnalysis"];
            /** Categories */
            categories: components["schemas"]["ComplaintCategory"][];
            /** Category */
            category: string;
            /** Review */
            review: string;
            sentiment: components["schemas"]["SentimentResult"];
            /** Similar Reviews */
            similar_reviews: components["schemas"]["SimilarReview"][];
        };
        /**
         * AnalyticsSummary
         * @description Headline numbers. Percentages are of *analysed* feedback, not of everything.
         */
        AnalyticsSummary: {
            /** Analysed */
            analysed: number;
            /** Average Rating */
            average_rating?: number | null;
            /** Earliest Feedback At */
            earliest_feedback_at?: string | null;
            /** Latest Feedback At */
            latest_feedback_at?: string | null;
            /** Not Analysed */
            not_analysed: number;
            sentiment_counts: components["schemas"]["SentimentCounts"];
            sentiment_percentages: components["schemas"]["SentimentPercentages"];
            /** Total Feedback */
            total_feedback: number;
            /** Unclassified */
            unclassified: number;
            /** Unclassified Percentage */
            unclassified_percentage: number;
        };
        /**
         * BatchPredictRequest
         * @description A batch of review texts to score with a single sentiment model.
         */
        BatchPredictRequest: {
            /**
             * Model
             * @default distilbert
             * @enum {string}
             */
            model: "vader" | "roberta" | "distilbert" | "finetuned" | "naive_bayes" | "logistic_regression";
            /** Texts */
            texts: string[];
        };
        /** Body_create_import_api_imports_post */
        Body_create_import_api_imports_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_create_import_api_v1_imports_post */
        Body_create_import_api_v1_imports_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * Category
         * @description A category available to this organisation's analysis.
         */
        Category: {
            /** Description */
            description: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Organisation Specific
             * @default false
             */
            organisation_specific: boolean;
            /** Source */
            source: string;
        };
        /**
         * CategoryStat
         * @description One row of the category breakdown.
         *
         *     `category_key` is null for the bucket holding results with no category: unclassified
         *     items and those the sentiment gate skipped. That bucket is the emerging-issue signal, so
         *     it is reported rather than dropped.
         */
        CategoryStat: {
            /** Average Confidence */
            average_confidence?: number | null;
            /** Category */
            category: string;
            /** Category Key */
            category_key?: string | null;
            /** Count */
            count: number;
            /** Percentage */
            percentage: number;
            sentiment_counts: components["schemas"]["SentimentCounts"];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Chat History */
            chat_history?: Record<string, never>[];
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /**
             * Grounded
             * @default true
             */
            grounded: boolean;
            /**
             * Retrieval Count
             * @default 0
             */
            retrieval_count: number;
            /** Sources */
            sources: components["schemas"]["RagSource"][];
        };
        /** ComplaintCategory */
        ComplaintCategory: {
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * CurrentUser
         * @description Who is signed in. `organisation` is null for a user who belongs to no organisation.
         *
         *     Deliberately no session token: it lives only in the HttpOnly cookie.
         */
        CurrentUser: {
            /** Email */
            email: string;
            organisation?: components["schemas"]["OrganisationContext"] | null;
        };
        /**
         * FeedbackDetail
         * @description One item, with the provenance a support conversation needs.
         */
        FeedbackDetail: {
            /**
             * Analysed
             * @default false
             */
            analysed: boolean;
            /** Analysed At */
            analysed_at?: string | null;
            /** Categorisation Skipped */
            categorisation_skipped?: string | null;
            /** Category */
            category?: string | null;
            /** Category Confidence */
            category_confidence?: number | null;
            /** Category Key */
            category_key?: string | null;
            /** Created At */
            created_at?: string | null;
            /** External Id */
            external_id?: string | null;
            /** Feedback At */
            feedback_at?: string | null;
            /** Id */
            id: string;
            /** Import Batch Id */
            import_batch_id?: string | null;
            /** Is Unclassified */
            is_unclassified?: boolean | null;
            /** Language */
            language?: string | null;
            /** Metadata */
            metadata?: Record<string, never>;
            /** Rating */
            rating?: number | null;
            /** Sentiment */
            sentiment?: string | null;
            /** Sentiment Confidence */
            sentiment_confidence?: number | null;
            /** Sentiment Model Version */
            sentiment_model_version?: string | null;
            /** Text */
            text: string;
        };
        /**
         * FeedbackItem
         * @description One piece of feedback with its current analysis, as a list row.
         */
        FeedbackItem: {
            /**
             * Analysed
             * @default false
             */
            analysed: boolean;
            /** Category */
            category?: string | null;
            /** Category Confidence */
            category_confidence?: number | null;
            /** Category Key */
            category_key?: string | null;
            /** Created At */
            created_at?: string | null;
            /** External Id */
            external_id?: string | null;
            /** Feedback At */
            feedback_at?: string | null;
            /** Id */
            id: string;
            /** Is Unclassified */
            is_unclassified?: boolean | null;
            /** Language */
            language?: string | null;
            /** Metadata */
            metadata?: Record<string, never>;
            /** Rating */
            rating?: number | null;
            /** Sentiment */
            sentiment?: string | null;
            /** Sentiment Confidence */
            sentiment_confidence?: number | null;
            /** Text */
            text: string;
        };
        /**
         * FeedbackPage
         * @description A page plus enough to render a pager without a second request.
         */
        FeedbackPage: {
            /** Has Next */
            has_next: boolean;
            /** Items */
            items: components["schemas"]["FeedbackItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            /** Total */
            total: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Data Loaded */
            data_loaded: boolean;
            /** Environment */
            environment: string;
            /** Index Ready */
            index_ready: boolean;
            /** Llm Ready */
            llm_ready: boolean;
            /** Status */
            status: string;
        };
        /**
         * ImportAccepted
         * @description The response to an upload: what was stored, what was not, and what happens next.
         *
         *     `job_id` and `analysis_status` describe the analysis this upload queued. For an identical
         *     re-upload they are null - nothing new was queued - and `duplicate_upload` is true.
         */
        ImportAccepted: {
            /** Analysis Status */
            analysis_status?: ("queued" | "running" | "succeeded" | "failed") | null;
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Duplicate Upload
             * @default false
             */
            duplicate_upload: boolean;
            /**
             * Duplicates In Database
             * @default 0
             */
            duplicates_in_database: number;
            /**
             * Duplicates In File
             * @default 0
             */
            duplicates_in_file: number;
            /** Filename */
            filename?: string | null;
            /** Import Id */
            import_id: string;
            /** Job Id */
            job_id?: string | null;
            /** Organisation Id */
            organisation_id: string;
            /** Row Errors */
            row_errors?: components["schemas"]["ImportRowError"][];
            /** Rows Imported */
            rows_imported: number;
            /** Rows Received */
            rows_received: number;
            /** Rows Rejected */
            rows_rejected: number;
            /** Status */
            status: string;
        };
        /**
         * ImportRowError
         * @description One rejected row, identified by the line number in the customer's own file.
         */
        ImportRowError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Row */
            row: number;
        };
        /**
         * ImportSummary
         * @description An import batch as a customer sees it.
         */
        ImportSummary: {
            /** Analysis Status */
            analysis_status?: ("queued" | "running" | "succeeded" | "failed") | null;
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Filename */
            filename?: string | null;
            /** Import Id */
            import_id: string;
            /** Job Id */
            job_id?: string | null;
            /** Organisation Id */
            organisation_id: string;
            /** Rows Imported */
            rows_imported: number;
            /** Rows Received */
            rows_received: number;
            /** Rows Rejected */
            rows_rejected: number;
            /** Status */
            status: string;
        };
        /**
         * JobSummary
         * @description Progress of background work. `error` is a summary - never internal detail.
         */
        JobSummary: {
            /** Attempts */
            attempts: number;
            /** Created At */
            created_at?: string | null;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Max Attempts */
            max_attempts: number;
            /** Organisation Id */
            organisation_id: string;
            /** Result */
            result?: Record<string, never> | null;
            /** Status */
            status: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * @example ana@example.com
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OrganisationContext
         * @description The organisation a signed-in user acts for. Decided by the server, never by the client.
         */
        OrganisationContext: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @description owner or member
             */
            role: string;
        };
        /** RagSource */
        RagSource: {
            /** Full Text */
            full_text: string;
            /** Platform */
            platform: string;
            /** Rating */
            rating: number;
            /** Review Id */
            review_id: string;
            /** Sentiment Label */
            sentiment_label: string;
            /** Similarity Score */
            similarity_score?: number | null;
            /** Text */
            text: string;
        };
        /**
         * RegisterRequest
         * @description A new account, and the name of the new organisation it will own.
         *
         *     Unknown fields are refused with 422: there is no way to name an existing organisation, an
         *     organisation id or a role here. The length caps are outer limits against huge payloads;
         *     the real rules (services/auth.py) produce the specific messages.
         */
        RegisterRequest: {
            /**
             * Email
             * @example ana@example.com
             */
            email: string;
            /**
             * Organisation Name
             * @example Acme Ltd
             */
            organisation_name: string;
            /**
             * Password
             * @description 12 to 128 characters.
             */
            password: string;
        };
        /** ReviewAnalysis */
        ReviewAnalysis: {
            /** Business Insight */
            business_insight: string;
            /** Department */
            department: string;
            /** Executive Summary */
            executive_summary: string;
            /** Keywords */
            keywords: string[];
            /** Priority */
            priority: string;
            /** Severity */
            severity: string;
            /** Summary */
            summary: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Model
             * @default distilbert
             * @enum {string}
             */
            model: "vader" | "roberta" | "distilbert" | "finetuned" | "naive_bayes" | "logistic_regression";
            /** Platform */
            platform?: ("amazon" | "yelp" | "twitter_airline") | null;
            /** Text */
            text: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Min Rating
             * @default 1
             */
            min_rating: number;
            /** Platform Filter */
            platform_filter?: ("amazon" | "yelp" | "twitter_airline") | null;
            /** Query */
            query: string;
            /** Sentiment Filter */
            sentiment_filter?: ("positive" | "neutral" | "negative") | null;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** SearchResult */
        SearchResult: {
            /** Platform */
            platform: string;
            /** Rating */
            rating: number;
            /** Review Id */
            review_id: string;
            /** Sentiment Label */
            sentiment_label: string;
            /** Similarity Score */
            similarity_score: number;
            /** Text */
            text: string;
        };
        /** SentimentCounts */
        SentimentCounts: {
            /**
             * Negative
             * @default 0
             */
            negative: number;
            /**
             * Neutral
             * @default 0
             */
            neutral: number;
            /**
             * Positive
             * @default 0
             */
            positive: number;
        };
        /** SentimentPercentages */
        SentimentPercentages: {
            /**
             * Negative
             * @default 0
             */
            negative: number;
            /**
             * Neutral
             * @default 0
             */
            neutral: number;
            /**
             * Positive
             * @default 0
             */
            positive: number;
        };
        /** SentimentResult */
        SentimentResult: {
            /** Confidence */
            confidence: number;
            /** Label */
            label: string;
            /** Model */
            model: string;
            scores: components["schemas"]["SentimentScore"];
        };
        /** SentimentScore */
        SentimentScore: {
            /** Negative */
            negative: number;
            /** Neutral */
            neutral: number;
            /** Positive */
            positive: number;
        };
        /** SimilarReview */
        SimilarReview: {
            /** Platform */
            platform: string;
            /** Rating */
            rating: number;
            /** Review Id */
            review_id: string;
            /** Sentiment Label */
            sentiment_label: string;
            /** Similarity Score */
            similarity_score: number;
            /** Text */
            text: string;
        };
        /**
         * TextRequest
         * @description Plain text input — used by endpoints that don't need platform/model choice.
         */
        TextRequest: {
            /** Text */
            text: string;
        };
        /**
         * TrendPoint
         * @description One bucket of a time series. Periods with no feedback are absent, not zero-filled.
         */
        TrendPoint: {
            /** Average Rating */
            average_rating?: number | null;
            /** Feedback Count */
            feedback_count: number;
            /**
             * Negative
             * @default 0
             */
            negative: number;
            /**
             * Neutral
             * @default 0
             */
            neutral: number;
            /**
             * Period
             * Format: date-time
             */
            period: string;
            /**
             * Positive
             * @default 0
             */
            positive: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    keywords_api_analytics_keywords_get: {
        parameters: {
            query?: {
                sentiment?: ("positive" | "neutral" | "negative") | null;
                n?: number;
                top_n?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platforms_api_analytics_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    rating_distribution_api_analytics_rating_distribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    sentiment_by_platform_api_analytics_sentiment_by_platform_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    summary_api_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    trends_api_analytics_trends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    rag_evaluation_api_evaluation_rag_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    retrieval_evaluation_api_evaluation_retrieval_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    sentiment_evaluation_api_evaluation_sentiment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_import_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_api_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_import_api_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_rag_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyse_api_sentiment_analyse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_api_sentiment_batch_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_sentiment_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_api_sentiment_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    predict_api_sentiment_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SentimentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_category_breakdown_api_v1_analytics_categories_get: {
        parameters: {
            query?: {
                sentiment?: ("positive" | "neutral" | "negative") | null;
                platform?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryStat"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: {
                sentiment?: ("positive" | "neutral" | "negative") | null;
                category_key?: string | null;
                platform?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_trend_api_v1_analytics_trend_get: {
        parameters: {
            query?: {
                interval?: "day" | "week" | "month";
                sentiment?: ("positive" | "neutral" | "negative") | null;
                category_key?: string | null;
                platform?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_current_user_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    register_account_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    list_items_api_v1_feedback_get: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description defaults to 50 */
                page_size?: number;
                sentiment?: ("positive" | "neutral" | "negative") | null;
                /** @description stable category key, not its name */
                category_key?: string | null;
                /** @description only items the categoriser could not place */
                unclassified?: boolean | null;
                /** @description filter on whether analysis has run */
                analysed?: boolean | null;
                /** @description matches metadata.platform from the upload */
                platform?: string | null;
                /** @description substring of the text */
                search?: string | null;
                /** @description feedback_at >= this */
                date_from?: string | null;
                /** @description feedback_at <= this */
                date_to?: string | null;
                min_rating?: number | null;
                max_rating?: number | null;
                sort?: "feedback_at" | "created_at" | "rating";
                order?: "desc" | "asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_item_api_v1_feedback__feedback_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imports_api_v1_imports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_import_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_api_v1_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_import_api_v1_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
