"""
Which engine, which models, which prompts produced a result.

Every `BatchAnalysis` carries this manifest, so a stored result can always be traced
back to what produced it - the question "why does this row disagree with that one?"
has an answer. Deliberately simple: constants plus the configured model names, read
at call time. No MLflow, no registry, no model-management platform.

Bump `ENGINE_VERSION` when the engine's behaviour changes, and the relevant prompt
version when a prompt's wording changes.
"""

from __future__ import annotations

import hashlib
import json
from functools import lru_cache

from feedbackiq.core.config import settings

# The engine's own contract: stage order, gating rules, output shapes.
ENGINE_VERSION = "1.0.0"

# Prompt identifiers. Change the value whenever the prompt text changes, so results
# generated by different wordings are distinguishable.
PROMPT_VERSIONS: dict[str, str] = {
    "item_analysis": "item-analysis-2026-09",
    "grounded_answer": "grounded-answer-2026-09",
    "condense_question": "condense-question-2026-09",
    "scope_guard": "scope-guard-2026-09",
}


@lru_cache(maxsize=1)
def sentiment_model_version() -> str:
    """
    An identifier for the fine-tuned sentiment model: its directory name plus a short
    digest of its small metadata files (`config.json`, `label_map.json`).

    Those files change whenever the architecture, the label order or the class count
    changes, which is what would silently invalidate stored results. The 256 MB
    weights file is deliberately not hashed - that would cost seconds on every call.
    """
    model_dir = settings.model_dir
    name = model_dir.name

    digest = hashlib.sha256()
    found_any = False
    for filename in ("config.json", "label_map.json"):
        path = model_dir / filename
        if path.exists():
            digest.update(path.read_bytes())
            found_any = True

    if not found_any:
        return f"{name}@unavailable"

    return f"{name}@{digest.hexdigest()[:12]}"


def manifest() -> dict[str, object]:
    """Everything needed to explain how a result was produced."""
    return {
        "engine": ENGINE_VERSION,
        "sentiment_model": sentiment_model_version(),
        "categoriser_model": settings.ZEROSHOT_MODEL,
        "embedding_model": settings.EMBEDDING_MODEL,
        "llm_model": settings.GROQ_MODEL,
        "prompts": dict(PROMPT_VERSIONS),
        "thresholds": {
            "category_confidence": settings.CATEGORY_CONFIDENCE_THRESHOLD,
            "retrieval_similarity": settings.SIMILARITY_THRESHOLD,
            "evidence_similarity": settings.ANALYSE_SIMILARITY_THRESHOLD,
        },
    }


def manifest_json() -> str:
    """The manifest as stable JSON, handy for logging or storing as a column."""
    return json.dumps(manifest(), sort_keys=True)
