"""
The migrations - migrations/versions/

What a deployment actually runs, so these tests run it the same way: an empty database,
`alembic upgrade head`, and nothing else. The tables are never created with
`Base.metadata.create_all()` here - that would test the models and leave the migration,
the thing a deployment depends on, unverified.

`test_the_migration_still_matches_the_models` is the one that earns its place over time:
it fails if someone edits db/models.py and forgets the migration, which is otherwise
discovered in production.
"""

from __future__ import annotations

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from feedbackiq.db import models  # noqa: F401  (registers the tables on Base.metadata)
from feedbackiq.db.base import Base

pytestmark = pytest.mark.integration

# Every table the models define, plus Alembic's own bookkeeping.
#
# Computed at import, so the models must be imported above. Without that import this file
# only passed when an earlier test module happened to import them first: run on its own,
# Base.metadata was empty and the expected schema was just {"alembic_version"}.
EXPECTED_TABLES = {table.name for table in Base.metadata.sorted_tables} | {"alembic_version"}


def tables_in(url: str) -> set[str]:
    engine = create_engine(url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_head_builds_the_whole_schema_from_an_empty_database(
    empty_database, run_migrations
):
    assert tables_in(empty_database) == set()

    run_migrations(empty_database)

    assert tables_in(empty_database) == EXPECTED_TABLES


def test_downgrade_removes_the_schema_and_re_upgrading_restores_it(
    empty_database, run_migrations
):
    run_migrations(empty_database)

    run_migrations(empty_database, "base")
    # alembic_version stays: it is how Alembic records that this database is now at base.
    assert tables_in(empty_database) == {"alembic_version"}

    run_migrations(empty_database)
    assert tables_in(empty_database) == EXPECTED_TABLES


def test_the_migration_still_matches_the_models(
    empty_database, run_migrations, alembic_config_for
):
    """A model changed without a migration is a bug this catches before deployment."""
    run_migrations(empty_database)

    try:
        command.check(alembic_config_for(empty_database))
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "db/models.py and migrations/ disagree - generate a migration with "
            f"`alembic revision --autogenerate`: {exc}"
        )


def test_the_schema_version_is_recorded(empty_database, run_migrations, alembic_config_for):
    run_migrations(empty_database)

    engine = create_engine(empty_database)
    try:
        with engine.connect() as connection:
            versions = (
                connection.execute(text("SELECT version_num FROM alembic_version"))
                .scalars()
                .all()
            )
    finally:
        engine.dispose()

    # Derived from the migration scripts, not hardcoded: pinning "0001" here meant this test
    # failed the moment a second migration was added, for no reason anyone cares about.
    head = ScriptDirectory.from_config(alembic_config_for(empty_database)).get_current_head()

    # Exactly one row: one linear history, no branch left half-applied.
    assert versions == [head]


def test_the_constraints_that_protect_tenants_survive_the_migration(
    empty_database, run_migrations
):
    """The partial indexes and the composite foreign key are not incidental - the
    persistence layer relies on them, so the migration has to carry them."""
    run_migrations(empty_database)

    engine = create_engine(empty_database)
    try:
        insp = inspect(engine)

        partial = {
            index["name"]: index["dialect_options"]["postgresql_where"]
            for table in insp.get_table_names()
            for index in insp.get_indexes(table)
            if index.get("dialect_options", {}).get("postgresql_where")
        }
        assert "uq_feedback_org_source_external" in partial
        assert "uq_categories_default_name" in partial
        assert "uq_analysis_results_current_feedback" in partial

        composite = [
            fk
            for fk in insp.get_foreign_keys("analysis_results")
            if fk["name"] == "fk_analysis_results_org_feedback"
        ]
        assert composite, "the composite tenant foreign key is missing"
        assert composite[0]["constrained_columns"] == ["organisation_id", "feedback_id"]
        assert composite[0]["referred_columns"] == ["organisation_id", "id"]
    finally:
        engine.dispose()
