"""stable category keys and import source hash

Gives every category a stable, machine-readable identity (`categories.key`) that is
independent of its display name, and records the SHA-256 of an uploaded file
(`import_batches.source_hash`) so an identical re-upload is recognisable.

Why `key` matters: stored analysis results point at a category row, and a caller's
taxonomy points at it by key. Renaming "Delivery Issues" to "Shipping & Delivery" then
changes a label and nothing else. Before this, the name *was* the identity, so a rename
would have orphaned every earlier result (recorded as limitation 3 of Milestone 5A).

**This is not the autogenerated version.** Alembic proposed adding `key` as NOT NULL with
no default, which fails on any database that already holds the 24 seeded categories - the
development database and every environment that ran Milestone 5A. It is done in the usual
three steps instead:

    1. add the column nullable
    2. backfill it
    3. make it NOT NULL, then add the unique indexes

The backfill carries the 24 key/name pairs explicitly rather than importing the packaged
taxonomy. A migration must keep doing the same thing years later, whatever the application
code has become; importing today's loader into it would make history depend on the present.
Rows the list does not cover (an organisation's own categories) get a key derived from
their name by the same rule that generated these pairs.

Revision ID: 0002
Revises: 0001
Created: 2026-09-13 13:32:53.121604+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The canonical taxonomy at version 1.1.0: (key, name). Keys were derived from these exact
# names once and are frozen from here on - a later rename must NOT regenerate them.
SEEDED_KEYS: tuple[tuple[str, str], ...] = (
    ('service_and_wait_time_delays', 'Service and Wait Time Delays'),
    ('salon_service_failures', 'Salon Service Failures'),
    ('product_taste_and_aroma_failures', 'Product Taste and Aroma Failures'),
    ('visual_quality_and_performance_failures', 'Visual Quality and Performance Failures'),
    ('hair_quality_and_performance_failures', 'Hair Quality and Performance Failures'),
    ('travel_disruption_issues', 'Travel Disruption Issues'),
    ('product_performance_failures', 'Product Performance Failures'),
    ('audio_performance_failures', 'Audio Performance Failures'),
    ('financial_institution_service_failures', 'Financial Institution Service Failures'),
    ('tablet_accessory_quality_failures', 'Tablet Accessory Quality Failures'),
    ('product_color_representation_failures', 'Product Color Representation Failures'),
    ('facial_protection_and_safety_failures', 'Facial Protection and Safety Failures'),
    ('home_network_connectivity_issues', 'Home Network Connectivity Issues'),
    ('product_fit_and_sizing_issues', 'Product Fit and Sizing Issues'),
    ('order_fulfillment_delays', 'Order Fulfillment Delays'),
    (
        'spray_bottle_continuous_spray_dryer_diffuser_fit_dryer',
        'Spray Bottle, Continuous Spray, Dryer Diffuser, Fit Dryer',
    ),
    ('accessory_attachment_and_fastening_failures', 'Accessory Attachment and Fastening Failures'),
    ('mounting_and_installation_problems', 'Mounting and Installation Problems'),
    ('gps_device_performance_failures', 'GPS Device Performance Failures'),
    ('laptop_cooling_system_failures', 'Laptop Cooling System Failures'),
    ('mirror_performance_failures', 'Mirror Performance Failures'),
    ('customer_service_apology_failures', 'Customer Service Apology Failures'),
    ('digital_platform_performance_failures', 'Digital Platform Performance Failures'),
    ('direct_messaging_access_issues', 'Direct Messaging Access Issues'),
)

# The same rule that produced those keys, in SQL: "&" and "/" become " and ", anything else
# that is not a letter or digit becomes "_", then runs of "_" collapse and the ends are
# trimmed. Used for any category the list above does not name.
DERIVE_KEY_SQL = """
    UPDATE categories
       SET key = trim(both '_' from regexp_replace(
                   regexp_replace(lower(name), '[&/]', ' and ', 'g'),
                   '[^a-z0-9]+', '_', 'g'))
     WHERE key IS NULL
"""


def upgrade() -> None:
    # --- categories.key: add, backfill, then constrain -----------------------------
    op.add_column('categories', sa.Column('key', sa.String(length=64), nullable=True))

    connection = op.get_bind()

    for key, name in SEEDED_KEYS:
        connection.execute(
            sa.text(
                "UPDATE categories SET key = :key "
                " WHERE organisation_id IS NULL AND name = :name AND key IS NULL"
            ),
            {"key": key, "name": name},
        )

    # Anything else (an organisation's own category, or a default that has been renamed
    # since 1.1.0) gets a key derived from its name.
    connection.execute(sa.text(DERIVE_KEY_SQL))

    op.alter_column('categories', 'key', existing_type=sa.String(length=64), nullable=False)

    # Created after the backfill, so they validate real data rather than an empty column.
    op.create_index(
        'uq_categories_default_key',
        'categories',
        ['key'],
        unique=True,
        postgresql_where=sa.text('organisation_id IS NULL'),
    )
    op.create_unique_constraint(
        'uq_categories_organisation_id_key', 'categories', ['organisation_id', 'key']
    )

    # --- import_batches.source_hash ------------------------------------------------
    # Nullable: a batch that did not come from a file has no hash. Indexed, not unique -
    # re-uploading the same file is legitimate, so the service decides what to do about it.
    op.add_column('import_batches', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.create_index(
        'ix_import_batches_organisation_id_source_hash',
        'import_batches',
        ['organisation_id', 'source_hash'],
        unique=False,
    )


def downgrade() -> None:
    # Children first, in the reverse order. Dropping `key` discards the stable identities;
    # names are untouched, so re-upgrading regenerates them from the list above.
    op.drop_index('ix_import_batches_organisation_id_source_hash', table_name='import_batches')
    op.drop_column('import_batches', 'source_hash')
    op.drop_constraint('uq_categories_organisation_id_key', 'categories', type_='unique')
    op.drop_index(
        'uq_categories_default_key',
        table_name='categories',
        postgresql_where=sa.text('organisation_id IS NULL'),
    )
    op.drop_column('categories', 'key')
